### ISSUE TITLE
do_adu_swuimage never seems to run

### ISSUE THREAD

**Issue by wasabii** [munit-solutions/meta-azure-device-update#11]
Have a dunfell project. Trying to get this ADU thing to work. I have my own image for update. It inherits adu-swupdate.

It doesn't run any of the swupdate stuff ever.

If I change my image to inherit from swupdate, a swu file is generated.

If I patch up the addtask/deltask lines in adu-swupdate.bbclass, the core swupdate stuff works (swu generated). However, the manifest is not generated.

I do not believe do_adu_swuimage is ever running. I'm not sure what could be up with it.

**Comment by SimonSimCity** [comment]
I was able to reproduce it - can you please check out if the problem still persists when applying the changes of my PR?

**Comment by wasabii** [comment]
This works.

**Comment by SimonSimCity** [comment]
@wasabii Please check the branch `dunfell` which contains the following commit: https://github.com/munit-solutions/meta-azure-device-update/commit/7d3595163ddc86fde94be9971acbdc6ae8e33aef

The commit should finally have fixed it by using the correct task-dependencies. Can you confirm?

**Comment by SimonSimCity** [comment]
Closing due to lack of feedback. Please let me know if the problem still persists.
