### ISSUE TITLE
bitbake adu-update-image fails with : swupdate cannot find image file: tmp/deploy/images/raspberrypi3/adu-update-image-raspberrypi3.ext4.gz

### ISSUE THREAD

**Issue by wbw455** [munit-solutions/meta-azure-device-update#17]
Hello,

I'm trying to follow your guide to build adu-base-image & adu-update-image for my raspberrypi.

$ bitbake adu-update-image
Loading cache: 100% |##########################################################################################################################| Time: 0:00:00
Loaded 3336 entries from dependency cache.
NOTE: Resolving any missing task queue dependencies

Build Configuration:
BB_VERSION           = "1.46.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "arm-poky-linux-gnueabi"
MACHINE              = "raspberrypi3"
DISTRO               = "poky"
DISTRO_VERSION       = "3.1.15"
TUNE_FEATURES        = "arm vfp cortexa7 neon vfpv4 thumb callconvention-hard"
TARGET_FPU           = "hard"
meta                 
meta-poky            
meta-yocto-bsp       = "dunfell:a743227d8137c3cb9500f7cdb4f79f7d8ed9a0cb"
meta-raspberrypi     = "dunfell:934064a01903b2ba9a82be93b3f0efdb4543a0e8"
meta-oe              
meta-networking      
meta-multimedia      
meta-python          = "dunfell:86b864a4d8c28185a4a464583fb86f73aa22847a"
meta-swupdate        = "dunfell:2e08de8582aa18871657ea8283ea35a050927d4f"
meta-azure-device-update = "dunfell-0.8.0:506ed3d4fde181a32610db43912d7c14ad8650c8"

Initialising tasks: 100% |#####################################################################################################################| Time: 0:00:01
Sstate summary: Wanted 173 Found 165 Missed 8 Current 1970 (95% match, 99% complete)
NOTE: Executing Tasks
WARNING: SWUPDATE_IMAGES_FSTYPES[adu-update-image-raspberrypi3] not set, setting to ext4.gz
WARNING: SWUPDATE_IMAGES_FSTYPES[adu-update-image-raspberrypi3] not set, setting to ext4.gz
WARNING: SWUPDATE_IMAGES_FSTYPES[adu-update-image-raspberrypi3] not set, setting to ext4.gz
WARNING: SWUPDATE_IMAGES_FSTYPES[adu-update-image-raspberrypi3] not set, setting to ext4.gz
WARNING: SWUPDATE_IMAGES_FSTYPES[adu-update-image-raspberrypi3] not set, setting to ext4.gz
WARNING: SWUPDATE_IMAGES_FSTYPES[adu-update-image-raspberrypi3] not set, setting to ext4.gz
WARNING: SWUPDATE_IMAGES_FSTYPES[adu-update-image-raspberrypi3] not set, setting to ext4.gz
WARNING: SWUPDATE_IMAGES_FSTYPES[adu-update-image-raspberrypi3] not set, setting to ext4.gz
WARNING: SWUPDATE_IMAGES_FSTYPES[adu-update-image-raspberrypi3] not set, setting to ext4.gz
WARNING: SWUPDATE_IMAGES_FSTYPES[adu-update-image-raspberrypi3] not set, setting to ext4.gz
ERROR: adu-update-image-1.0-r0 do_swuimage: swupdate cannot find image file: /linux/build/yocto/rpi3/build-rpi/tmp/deploy/images/raspberrypi3/adu-update-image-raspberrypi3.ext4.gz
ERROR: Logfile of failure stored in: /linux/build/yocto/rpi3/build-rpi/tmp/work/raspberrypi3-poky-linux-gnueabi/adu-update-image/1.0-r0/temp/log.do_swuimage.5952
ERROR: Task (/linux/build/yocto/rpi3/sources/meta-azure-device-update/recipes-extended/images/adu-update-image.bb:do_swuimage) failed with exit code '1'
NOTE: Tasks Summary: Attempted 5403 tasks of which 5393 didn't need to be rerun and 1 failed.

For some reason the adu-update-image gets passed to swupdate instead of adu-base-image.

Do you have any ideas what could cause this?

Thanks,

**Comment by SimonSimCity** [comment]
I can't remember having this problem, neither was I able to reproduce it as of now. Are you able to create a repo where I can reproduce it?

**Comment by wbw455** [comment]
Hello Simon,

I got rid of this error by inheriting swupdate instead of adu-swupdate in the adu-update.image recipe. I got the idea from looking at your dunfell branch.

Closing this case since it solved the problem.
