### ISSUE TITLE
[Dunfell] Variable in adu-swupdate.bbclass is unset and causes issues when building the update image

### ISSUE THREAD

**Issue by Pan5ky** [munit-solutions/meta-azure-device-update#4]
Hi, 
I'm having difficulties building the update image. I tracked the problem down to this line: `imgdeploydir = d.getVar('IMGDEPLOYDIR', True)` in [adu-swupdate.bbclass](https://github.com/munit-solutions/meta-azure-device-update/blob/dunfell/classes/adu-swupdate.bbclass). At least for me, `IMGDEPLOYDIR` does not have a value and the recipe runs into a problem when it tries to pass that variable to some python library. I'm not sure if this is the right way to fix this but i got it working by changing it to `imgdeploydir = d.getVar('SWUDEPLOYDIR', True)`. Can someone confirm that this is an actual issue and not just user error on my part? And maybe someone has a better idea on how to handle this issue. I'm new to the whole bitbake toolchain and do not know how and where `IMGDEPLOYDIR` should get its value from. I'm happy to make a pullrequest if this turns out to be an actual issue.

**Comment by SimonSimCity** [comment]
Just now looking at it as I heard also others having trouble here ... That means you have the `meta-swupdate` layer at least at the commit `36ffe358924689fca043ed3de145caec4a0e4efe` if you're on `zeus`, `53c5416014e76ab0c1d8771836fc5c52110e966a` if you're on `hardknott`, `e12973e43356c9020bb0317d0046942b3b265e9b` for `honister`, right?

**Comment by SimonSimCity** [comment]
Maybe its good to add a fallback here, that the script takes `SWUDEPLOYDIR` and if its empty, it falls back to `IMGDEPLOYDIR`. If you create a PR here, please also add a tiny comment to the code and the full explanation in the second line of your commit message.

**Comment by SimonSimCity** [comment]
Fixed by merging #7
